name: Forth-workflow
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the Title
        required: true
        default: 'Default Title'

jobs:
  run-scheduled-command:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled Event vars
        run: |
          echo ${{ inputs.titleCustom }}